-- Canton Workshop: Filmmaking in the Real World (May 23, 2026)
INSERT INTO experiences (
  slug,
  title,
  type,
  status,
  start_date,
  end_date,
  country,
  city,
  capacity,
  registered_count,
  venue,
  venue_address,
  start_time,
  end_time,
  hero_image,
  theme,
  price_display,
  duration_display,
  learning_outcomes,
  itinerary,
  faqs,
  gear_note,
  overview,
  seo_description
) VALUES (
  'filmmaking-canton',
  'Filmmaking in the Real World',
  'workshop',
  'published',
  '2026-05-23',
  '2026-05-23',
  'United States',
  'Canton, Georgia',
  20,
  0,
  'River Church Canton — Community Room',
  '2335 Sixes Rd, Canton, GA 30144',
  '2:00 PM',
  '4:00 PM',
  '/images/hero-canton-workshop.avif',
  'Camera Basics & Documentary Storytelling',
  '$50',
  '2 hours',
  '["Understand camera basics and how to get great shots with any gear","Experience what a real set looks and feels like","Learn documentary storytelling techniques","Start creating better video with what you already have","Connect with fellow creators in your area"]'::jsonb,
  '[{"day":1,"title":"Workshop Session","description":"Full 2-hour hands-on workshop covering camera fundamentals, set experience, and documentary storytelling.","location":"Canton, GA"}]'::jsonb,
  '[{"question":"Do I need to bring any equipment?","answer":"No gear needed — everything will be provided for the workshop."},{"question":"What is the cost?","answer":"The workshop is $50 per person."},{"question":"How long is the workshop?","answer":"The workshop is approximately 2 hours."},{"question":"Who is this for?","answer":"Students, creators, church media teams, small business owners, photographers, and anyone in Canton or the surrounding area who wants to understand how real productions work."}]'::jsonb,
  'No gear needed — everything will be provided!',
  'Camera basics, set experience, documentary storytelling, and how to start creating with what you already have. A 2-hour in-person workshop for students, creators, church media teams, small business owners, photographers, and anyone who wants to understand how real productions work and start making better video.',
  'A 2-hour in-person workshop in Canton, GA covering camera basics, real set experience, documentary storytelling, and how to start creating better video with what you already have. $50.'
)
ON CONFLICT (slug) DO NOTHING;
